spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimdonghyeon98@gmail.com
    password: rovjrkeqmatylzuz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

custom:
  jwt:
    secretKey: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey