spring:
  config:
    import:
    - optional:classpath:/application-secret1.yml
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create